apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "snmalik98@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "zmdu plfc anay pifq"
type: Opaque

